### ISSUE TITLE
Failed to set up: sign verification failed

### ISSUE THREAD

**Issue by JossPer0** [AlexxIT/SonoffLAN#924] opened 2022-07-27 13:32 UTC
Everything seems to be working but am getting a the above message, there is a reconfigure option "Attention required". I sign in there and then get the message "This account is already configured.
![Screenshot 2022-07-27 153147](https://user-images.githubusercontent.com/37881812/181259715-65788de3-830f-43b8-8b92-e5bd63fd4ca0.png)

**Comment by pops3449** [comment] 2022-07-27 23:11
having the same issue

**Comment by vitoralvimb** [comment] 2022-07-28 00:06
Same issue here!

**Comment by joelhauxwell** [comment] 2022-07-28 06:14
Same issue here

**Comment by JGBlignault** [comment] 2022-07-28 10:34
Same for me

**Comment by VdR1960** [comment] 2022-07-30 10:50
And me

**Comment by NMichas** [comment] 2022-07-30 19:22
Same here, note this is a duplicate of #878.

**Comment by pops3449** [comment] 2022-07-30 23:37
After updating all, it's working fine

**Comment by VdR1960** [comment] 2022-08-01 11:06
Same here. Update HA core and OS, now ok.

**Comment by joelhauxwell** [comment] 2022-08-04 19:33
> Same here. Update HA core and OS, now ok.

My system is all up to date - I still have the issue

**Comment by Tchitan** [comment] 2022-08-10 13:04
Same as above

**Comment by maxcim32** [comment] 2022-08-12 02:26
Same as above - have two eWelink accounts in the same HA, one has this sign in problem the other does not. Most devices continue to work bur Zigbee may have a problem, still investigating.

**Comment by zheka24** [comment] 2022-11-04 08:47
Since yesterday we have another problem. It is password error

**Comment by AlexxIT** [comment] 2023-03-31 10:33
Can't reproduce problem on latest integration version.
Please reopen the issue if there are still any problems.

**Closed by AlexxIT** 2023-03-31 10:33 UTC
Labels: bug
