### ISSUE TITLE
State does not get refreshed until the integration is manually reloaded

### ISSUE THREAD

**Issue by pblxptr** [AlexxIT/SonoffLAN#1072] opened 2022-12-30 12:49 UTC
Hello, I've been using SonoffLAN integration in order to use Sonoff S26 R2 using 'Auto' mode. The problem is that the state of the switch is not shown correctly.  E.g. I manually toggle the switch, then it physically changes its state, but Home Assistants keeps showing the previous state. The only remedy for this I've found so far is to reload the SonoffLAN integration, which 'solves' the problem, and HA starts to show the correct state. However, it doesn't solve the problem permanently because it occurs again and again. I see no errors in the Log related to this integration.

**Comment by roscio1975** [comment] 2022-12-30 14:38
Occurs also to me (only on devices connected thru zigbee bridge).
The error in logs is:

"errors": [
      {
        "name": "homeassistant",
        "message": [
          "Error doing job: Task exception was never retrieved"
        ],
        "level": "ERROR",
        "source": [
          "custom_components/sonoff/remote.py",
          143
        ],
        "timestamp": 1672394881.4810483,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/local.py\", line 221, in _process_zeroconf\n    self.dispatcher_send(SIGNAL_UPDATE, msg)\n  File \"/config/custom_components/sonoff/core/ewelink/base.py\", line 59, in dispatcher_send\n    handler(*args, **kwargs)\n  File \"/config/custom_components/sonoff/core/ewelink/__init__.py\", line 242, in local_update\n    self.dispatcher_send(did, params)\n  File \"/config/custom_components/sonoff/core/ewelink/base.py\", line 59, in dispatcher_send\n    handler(*args, **kwargs)\n  File \"/config/custom_components/sonoff/core/entity.py\", line 108, in internal_update\n    self.set_state(params)\n  File \"/config/custom_components/sonoff/remote.py\", line 143, in set_state\n    self.hass.bus.async_fire(\"sonoff.remote\", data)\nAttributeError: 'NoneType' object has no attribute 'bus'\n",
        "count": 1,
        "first_occurred": 1672394881.4810483
      },
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud processing error"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/light.py",
          379
        ],
        "timestamp": 1672396021.2785103,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 286, in run_forever\n    await self._process_ws_msg(resp)\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 346, in _process_ws_msg\n    self.dispatcher_send(SIGNAL_UPDATE, data)\n  File \"/config/custom_components/sonoff/core/ewelink/base.py\", line 59, in dispatcher_send\n    handler(*args, **kwargs)\n  File \"/config/custom_components/sonoff/core/ewelink/__init__.py\", line 188, in cloud_update\n    self.dispatcher_send(did, params)\n  File \"/config/custom_components/sonoff/core/ewelink/base.py\", line 59, in dispatcher_send\n    handler(*args, **kwargs)\n  File \"/config/custom_components/sonoff/core/entity.py\", line 108, in internal_update\n    self.set_state(params)\n  File \"/config/custom_components/sonoff/light.py\", line 379, in set_state\n    state = params[effect]\nKeyError: 'white'\n",
        "count": 12,
        "first_occurred": 1672393570.7312646
      }
    ],
    "device": {
      "uiid": 3026,
      "params": {
        "bindInfos": "***",
        "subDevId": "26679428004b12003026",
        "parentid": "1001703423",
        "lock": 0,
        "trigTime": "1672409940750",
        "battery": 100,
        "supportPowConfig": 1
      },
      "model": "ZIGBEE_DOOR_AND_WINDOW_SENSOR",
      "online": true,
      "localtype": null,
      "deviceid": "a480046422"
    }
  }
}

**Comment by ianvnza** [comment] 2022-12-31 07:53
> Hello, I've been using SonoffLAN integration in order to use Sonoff S26 R2 using 'Auto' mode. The problem is that the state of the switch is not shown correctly. E.g. I manually toggle the switch, then it physically changes its state, but Home Assistants keeps showing the previous state. The only remedy for this I've found so far is to reload the SonoffLAN integration, which 'solves' the problem, and HA starts to show the correct state. However, it doesn't solve the problem permanently because it occurs again and again. I see no errors in the Log related to this integration.

I have been seeing the same thing happen on my installation. No errors in the log related to SonoffLan, but my sonoff devices report incorrect statuses once our power goes out. Sonoff POWR2 and Micro devices is being used. Only way to get the correct status is either rebooting the homeassistant instance or reloading the SonoffLan integration. This has been happening the past week. So possible the last homeasisstant update broke something?

**Comment by matteocopelli** [comment] 2023-01-02 11:47
i have the same problem with SNZB-04 and SNZB-02

**Comment by nomad64** [comment] 2023-01-03 01:54
I have the same problem with my iFan04 controllers. If I toggle the light or fan state via the remote control, the state in HA does not change. However, the state in eWeLink changes correctly.

SonoffLAN is configured in `auto` mode and the iFan controllers are running stock firmware v3.5.0.

**Comment by madchap** [comment] 2023-01-04 06:41
Same issue, temp sensor, motion sensors and lights through a basic bridge.

**Comment by Urghesgrunt** [comment] 2023-01-09 16:12
same problem with sonoff mini zb-04 (i use sonoff zigbee bridge-p); 
all my device of this model are under "light" domain without any "helper", instead the wifi counterpart (sonoff wifi mini r2) is in "switch" domain; if I toggle my physical switch HA change the state and the toggle correctly the light on/off, but interacting via HA the on/off toggle is broken and use a mix of click and double click to effectively toggle the light on/off

I'm a new HA user, installed just a few days ago, so I cannot say if this problem is caused by the recent update

**Comment by itsmartinho** [comment] 2023-01-12 08:38
Exact same issue here. 
And actually having trouble to make the devices get the proper status. Everything is ok on Ewelink and all my devices show as unavailable for 12h. Restarted HA, restarted the Sonoff Integration, same results. 

This was after a simple outtage.

**Comment by asteinarson** [comment] 2023-01-12 15:52
I think (at least the issue at the top) is the issue with updates to local ZeroConf (mDNS). See issues #999 and  #839. They were (IMHO) not solved but rather explained. And the suggested workaround was to shift into cloud mode (as many non flashed Sonoff devices has stopped working in LAN mode - following updates of dependencies). 

From my perspective (I manage a house with pretty static setup for heating, temp and humidity monitoring), a more direct workaround of manually specifying the IP address of each Sonoff switch would be preferred. (I don't move the sensors/switches around so the mDNS feature is really not of much use - after initial setup. Most routers allow for hard binding IP addresses for selected devices as well).  (It is much more useful for me to know the local system works also when my network connection is down).

**Comment by BLDCompsol** [comment] 2023-01-12 16:17
Same with me. I am experiencing a number of issues with Sonoff Lan Integration on HA. I cant be sure but it would seem to coincide with recent upgrades (last couple of months, unfortunately cant be certain which one though)
For example, when turning on a switch ( e.g. POWR2) from a dashboard the switch will turn on and stay on but the UI initially shows it as On then after a couple of seconds it shows it as Off.
If I then go to integrations->sonoff Lan ->Reload the UI will correctly reflect the current state of the switch. If I then continuously toggle the switch the UI will reflect the current state as it should BUT only for a short time (a minute or 2) after which UI reverts back to what I described above.
The POWR2 is a power monitor device and, it seems, HA no longer receivers the sensor data when it is doing what I described above.
Any assistance would be much appreciated.
I have also noticed that when this issue is happening no entries appear in the history log.
I have recorded video screen grab that demonstrates what is happening. Due to its size I couldnt attach it but it can be found here on my youtube channel https://youtu.be/QOYB4wJO_h0
Please Note: Although Ive described just one device it can happen with any Sonoff wifi device

**Comment by ajcorrea** [comment] 2023-01-12 17:48
I´m having same issue with Sonoff Zigbee sensors and Sonoff Bridge. After reloading integration, it´s works for a while but stops works after some time.

Setup using "auto" mode. My LAN networks are 100% transparent (no nat).

I don´t see any error messages on log.

I´m using Raspberry PI4 with HA. 

Others sensors like Sonoff Mini R2 are running fine. 

Attached de diagnostic of integration. 


`    "errors": [
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud processing error"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/climate.py",
          169
        ],
        "timestamp": 1673482238.3811173,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 286, in run_forever\n    await self._process_ws_msg(resp)\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 346, in _process_ws_msg\n    self.dispatcher_send(SIGNAL_UPDATE, data)\n  File \"/config/custom_components/sonoff/core/ewelink/base.py\", line 59, in dispatcher_send\n    handler(*args, **kwargs)\n  File \"/config/custom_components/sonoff/core/ewelink/__init__.py\", line 188, in cloud_update\n    self.dispatcher_send(did, params)\n  File \"/config/custom_components/sonoff/core/ewelink/base.py\", line 59, in dispatcher_send\n    handler(*args, **kwargs)\n  File \"/config/custom_components/sonoff/core/entity.py\", line 108, in internal_update\n    self.set_state(params)\n  File \"/config/custom_components/sonoff/climate.py\", line 169, in set_state\n    cache[\"temperature\"] + cache.get(\"tempCorrection\", 0)\nTypeError: can only concatenate str (not \"int\") to str\n",
        "count": 5,
        "first_occurred": 1673478505.2409053
`

[config_entry-sonoff-1ac96566f1eebfc91a308be93930e64d.json (1).txt](https://github.com/AlexxIT/SonoffLAN/files/10404461/config_entry-sonoff-1ac96566f1eebfc91a308be93930e64d.json.1.txt)

**Comment by Muji86** [comment] 2023-01-13 09:22
I see this behavior when using a VPN.
As soon as I disconnect from VPN it refreshes fine.
Not sure why, it happens even if using "cloud" mode

**Comment by Acheron83** [comment] 2023-01-17 08:43
Same issue here. Sonoff ZB bridge (not flashed) and 3 Aqara temp/humidity sensors. 

Values are correctly reported to eWeLink (and passed to Google Assistant), but remain unchanged on Home Assistant until the integration is reloaded.

My current workaround is an automation to reload the devices every 15min:
`alias: Reload Temps
description: ""
trigger:
  - platform: time_pattern
    minutes: "15"
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      device_id:
        - x
        - y
        - z
mode: single
`

**Comment by madchap** [comment] 2023-01-17 13:46
Yea, I reload every 2mn... but with motion sensors driving lights, it still is not a good solution :-/ (at least for me)

**Comment by madchap** [comment] 2023-01-17 13:46
@AlexxIT anything we can get you to help? Thanks!

**Comment by itsmartinho** [comment] 2023-01-17 13:49
I don't think constantly pinging / asking Alexx for questions is actually gonna help.
They have us an alpha fix extremely fast, now we gotta wait for a stable release. Keep in mind that demanding / asking for ETA's is generally perceived as rude, specially if the person's working for free.

Just wait. It'll get fixed, Alexx always does.

**Comment by BLDCompsol** [comment] 2023-01-17 14:01
>they gave us an alpha fix extremely fast, now we gotta wait for a stable release
What version are you referring to and when was it released?

**Comment by madchap** [comment] 2023-01-17 14:28
@itsmartinho - Could you please point to the alpha fix? I may have missed it.

At any rate, definitely didn't want to appear to be "rude" and not asking for any timeline (I use to maintain other OSS projects). I only thought to bring a bit of visibility to this issue given that it seems more and more people experience the issue, and that it may be a vector of priority for Alex.

**Comment by ewelink-toac** [comment] 2023-02-02 08:53
Hi @BLDCompsol I'm really struggling with this issue, which seems to be in many threads. Would you be so kind as to point me to the "Alpha Fix" you refer to.

**Comment by BLDCompsol** [comment] 2023-02-02 09:58
> Hi @BLDCompsol I'm really struggling with this issue, which seems to be in many threads. Would you be so kind as to point me to the "Alpha Fix" you refer to.

Youve read the messages wrong, I also want to know where it is

**Comment by AlexxIT** [comment] 2023-02-04 05:39
You provide a lot of different errors in one issue - not a good idea.
Problems: with new bulb API, with new NS panel API, with Sonoff RF. All of them fixed in latest master and will be in next release

**Comment by roscio1975** [comment] 2023-02-04 08:51
> You provide a lot of different errors in one issue - not a good idea. Problems: with new bulb API, with new NS panel API, with Sonoff RF. All of them fixed in latest master and will be in next release

Thanks! Is any way to "buy you a coffe" for your work?

**Comment by AlexxIT** [comment] 2023-02-04 10:52
No way after february 2022

**Comment by ewelink-toac** [comment] 2023-02-04 11:02
Hi @AlexxIT I am using Sonoff 3.3.1. I am not familiar with which version is a Master, and where to download, but I am desperate to resolve my issue which developed with the Sonoff integration a week or two ago where it is refreshing info from the POWR320D units. I am busy looking at an alternate product (probably Shelley) so that I can get this working. If there is a fix/update I could try I would really appreciate it as  I'm desperate.
Wierdly, I have a 2nd instance running at my home with many Sonoff devices (no POWR320D's or Dual R3), and all works perfectly with same versions of HA/HACS/Sonoff-LAN.
Thank-you for your effort to date.

**Comment by ewelink-toac** [comment] 2023-02-04 11:03
> > Hi @BLDCompsol I'm really struggling with this issue, which seems to be in many threads. Would you be so kind as to point me to the "Alpha Fix" you refer to.
> 
> Youve read the messages wrong, I also want to know where it is

Hi @BLDCompsol , sorry was too quick on the KB, when I saw a possible fix.

**Comment by AlexxIT** [comment] 2023-02-04 11:37
Most of the problems are due to an upgrade of some device. It starts to cause integration errors. If you don't have the problem device, everything works fine.

You need to help yourself, find error and post it here. So I can fix it. Because I don't have many new devices form Sonoff.

**Comment by AlexxIT** [comment] 2023-02-06 03:56
I hope this should be fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0

**Closed by AlexxIT** 2023-02-06 03:56 UTC
Labels: bug
