### ISSUE TITLE
After 2024.1.0 ZIGBEE_MOBILE_SENSOR status not synced

### ISSUE THREAD

**Issue by razim7** [AlexxIT/SonoffLAN#1291] opened 2024-01-04 08:12 UTC
After 2024.1.0 ZIGBEE_MOBILE_SENSOR status not synced stays clear all the time

**Comment by hmmbob** [comment] 2024-01-04 08:21
Duplicate of #1285 and #1288, please close this issue and follow #1288

**Comment by AlexxIT** [comment] 2024-01-04 18:41
#1285

**Closed by AlexxIT** 2024-01-04 18:41 UTC
Labels: duplicate
