### ISSUE TITLE
After upgrading to 2024.1, there is no feedback on the switch status

### ISSUE THREAD

**Issue by Gzzloveyyt** [AlexxIT/SonoffLAN#1289] opened 2024-01-04 04:57 UTC
After upgrading to 2024.1, there is no feedback on the switch status. For example, when I turn on the light, the light comes on, but the status is not synchronized

**Comment by ajcorrea** [comment] 2024-01-04 05:28
Same problem here after upgrade to 2024.1

**Comment by ajcorrea** [comment] 2024-01-04 05:37
When click on a switch (light switch):

`
Jan  4 02:36:15 homeassistant homeassistant[688]: #033[31m2024-01-04 02:36:15.476 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Jan  4 02:36:15 homeassistant homeassistant[688]: Traceback (most recent call last):
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 342, in _process_ws_msg
Jan  4 02:36:15 homeassistant homeassistant[688]:     self.dispatcher_send(SIGNAL_UPDATE, data)
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/config/custom_components/sonoff/core/ewelink/base.py", line 63, in dispatcher_send
Jan  4 02:36:15 homeassistant homeassistant[688]:     handler(*args, **kwargs)
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 229, in cloud_update
Jan  4 02:36:15 homeassistant homeassistant[688]:     self.dispatcher_send(did, params)
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/config/custom_components/sonoff/core/ewelink/base.py", line 63, in dispatcher_send
Jan  4 02:36:15 homeassistant homeassistant[688]:     handler(*args, **kwargs)
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/config/custom_components/sonoff/core/entity.py", line 119, in internal_update
Jan  4 02:36:15 homeassistant homeassistant[688]:     self._async_write_ha_state()
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
Jan  4 02:36:15 homeassistant homeassistant[688]:     state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
Jan  4 02:36:15 homeassistant homeassistant[688]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 994, in __async_calculate_state
Jan  4 02:36:15 homeassistant homeassistant[688]:     capability_attr = self.capability_attributes
Jan  4 02:36:15 homeassistant homeassistant[688]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 238, in capability_attributes
Jan  4 02:36:15 homeassistant homeassistant[688]:     self.native_min_value, floor_decimal, device_class
Jan  4 02:36:15 homeassistant homeassistant[688]:     ^^^^^^^^^^^^^^^^^^^^^
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/backports/functools.py", line 70, in __get__
Jan  4 02:36:15 homeassistant homeassistant[688]:     val = self.func(instance)
Jan  4 02:36:15 homeassistant homeassistant[688]:           ^^^^^^^^^^^^^^^^^^^
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 269, in native_min_value
Jan  4 02:36:15 homeassistant homeassistant[688]:     if hasattr(self, "_attr_native_min_value"):
Jan  4 02:36:15 homeassistant homeassistant[688]:        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
Jan  4 02:36:15 homeassistant homeassistant[688]:     return getattr(o, private_attr_name)
Jan  4 02:36:15 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
Jan  4 02:36:15 homeassistant homeassistant[688]:     return getattr(o, private_attr_name)
Jan  4 02:36:15 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan  4 02:36:15 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 338, in _getter
Jan  4 02:36:15 homeassistant homeassistant[688]:     return getattr(o, private_attr_name)
Jan  4 02:36:15 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan  4 02:36:15 homeassistant homeassistant[688]:   [Previous line repeated 975 more times]
Jan  4 02:36:15 homeassistant homeassistant[688]: RecursionError: maximum recursion depth exceeded#033[0m
`

**Comment by Netfalls** [comment] 2024-01-04 05:56
Same here

**Comment by hmmbob** [comment] 2024-01-04 06:51
Duplicate of #1285 and #1288

**Comment by Gzzloveyyt** [comment] 2024-01-04 06:56
May I ask when the author can fix this issue? It's very tricky, all the lights in the house are using sonoff

**Comment by hmmbob** [comment] 2024-01-04 07:02
When he has time to do so (the author is making this component in his free time, voluntarily) - if it is this tricky stay on HA 2023.12.

**Comment by hmmbob** [comment] 2024-01-04 07:05
Furthermore, please close this issue and track #1288 instead

**Closed** 2024-01-04 07:06 UTC
