### ISSUE TITLE
Add Support for new device

### ISSUE THREAD

**Issue by Nine9d** [AlexxIT/SonoffLAN#1312] opened 2024-01-08 02:37 UTC
Dear Alexx, 

Hope can add support SONOFF Zigbee Human Presence Sensor | SNZB-06P.

Currently it not show anything for this device.

Thanks

**Comment by olalofgren** [comment] 2024-01-08 21:13
Duplicate of:
https://github.com/AlexxIT/SonoffLAN/issues/1245

**Closed** 2024-02-13 05:24 UTC
Labels: duplicate
