### ISSUE TITLE
Sonoff DW2 not change state after some times must reboot Home Assistant

### ISSUE THREAD

**Issue by antoweb** [AlexxIT/SonoffLAN#666] opened 2022-01-08 22:25 UTC
From last update sonoff dw2 door sensor cannot change state if Home Assistant is up and running from some times. For recognize the state i have to reboot Home Assistant

**Comment by Weedfly** [comment] 2022-01-12 08:15
HI, did you manage to solve this issue? I have the same - have to restart HA every day for my automations to work...

**Comment by Locoblade** [comment] 2022-01-14 22:30
I have a similar issue since upgrading HA to 2021.12.9 yesterday, I only have one Sonoff WiFi device (TH16 switch/temperature probe) that connects through SonoffLAN and for the past 4 months since installing its been rock solid, but the past two nights around the same time each night the device stopped reporting in to HA even though it's still visible in the ewelink app, and both time a reboot of HA bought it back online

**Comment by antoweb** [comment] 2022-01-14 22:44
> I have a similar issue since upgrading HA to 2021.12.9 yesterday, I only have one Sonoff WiFi device (TH16 switch/temperature probe) that connects through SonoffLAN and for the past 4 months since installing its been rock solid, but the past two nights around the same time each night the device stopped reporting in to HA even though it's still visible in the ewelink app, and both time a reboot of HA bought it back online

Past two night ewelink server had problems doesnt depend by HA

**Comment by Locoblade** [comment] 2022-01-14 23:21
Ah OK thanks so maybe just a coincidence then although I always assumed using SonofLAN meant HA's connection to the device was local and didn't rely on the eWeLink cloud, is that not how it works?

**Comment by AlexxIT** [comment] 2022-01-18 13:24
TH may have some problems with Temp/Hum update via LAN in latest release. But this problems should be fixed in latest master version

**Comment by Phil-m-pinto** [comment] 2022-04-23 11:53
I believe the DW2s rely on the Cloud ( see notes)


Tested (only Cloud)

These devices only work through the cloud!

[Sonoff L1](https://www.itead.cc/sonoff-l1-smart-led-light-strip.html) (color, brightness, effects) fw 2.7.0
[Sonoff B1](https://www.itead.cc/sonoff-b1.html) (color, brightness, color temp) fw 2.6.0
[Sonoff SC](https://www.itead.cc/sonoff-sc.html) (five sensors) fw 2.7.0
[Sonoff DW2](https://www.itead.cc/sonoff-dw2.html)
[King Art - King Q4 Cover](https://www.aliexpress.com/item/32956776611.html) (pause, position) fw 2.7.0
[KING-M4](https://www.aliexpress.com/item/33013358523.html) (brightness) fw 2.7.0
[Eachen WiFi Door/Window Sensor](https://ewelink.eachen.cc/product/eachen-wifi-smart-door-window-sensor-wdw-ewelink/)
[Essential Oils Diffuser](https://www.amazon.co.uk/dp/B07WF7MQ17) (fan and color light) fw 2.9.0
[Smart USB Mosquito Killer](https://www.aliexpress.com/item/33037963105.html)
[Smart Bulb RGB+CCT](https://www.aliexpress.com/item/4000764330397.html)

**Comment by antoweb** [comment] 2022-04-23 12:08
> I believe the DW2s rely on the Cloud ( see notes)
> 
> Tested (only Cloud)
> 
> These devices only work through the cloud!
> 
> [Sonoff L1](https://www.itead.cc/sonoff-l1-smart-led-light-strip.html) (color, brightness, effects) fw 2.7.0 [Sonoff B1](https://www.itead.cc/sonoff-b1.html) (color, brightness, color temp) fw 2.6.0 [Sonoff SC](https://www.itead.cc/sonoff-sc.html) (five sensors) fw 2.7.0 [Sonoff DW2](https://www.itead.cc/sonoff-dw2.html) [King Art - King Q4 Cover](https://www.aliexpress.com/item/32956776611.html) (pause, position) fw 2.7.0 [KING-M4](https://www.aliexpress.com/item/33013358523.html) (brightness) fw 2.7.0 [Eachen WiFi Door/Window Sensor](https://ewelink.eachen.cc/product/eachen-wifi-smart-door-window-sensor-wdw-ewelink/) [Essential Oils Diffuser](https://www.amazon.co.uk/dp/B07WF7MQ17) (fan and color light) fw 2.9.0 [Smart USB Mosquito Killer](https://www.aliexpress.com/item/33037963105.html) [Smart Bulb RGB+CCT](https://www.aliexpress.com/item/4000764330397.html)

Yes but rebooting HA the state is updated

**Comment by AlexxIT** [comment] 2022-04-23 15:24
@antoweb show your config

**Comment by antoweb** [comment] 2022-04-23 17:26
> @antoweb show your config

No particular config. Just connected with this integration and trigger the state

**Comment by AlexxIT** [comment] 2022-04-23 17:52
Have you set mode in config?

**Comment by AlexxIT** [comment] 2022-05-02 05:41
Fixed in latest master-version

**Closed by AlexxIT** 2022-05-02 05:41 UTC
Labels: question

**Comment by nicolacampagnolo** [comment] 2022-09-24 02:55
Hi everybody,
I have the same problem.

How do you solve this problem?

**Comment by lazmo88** [comment] 2022-12-07 14:18
Can report the same problem for DW2. After a while the state becomes unresponsive and reloading integration is required to get it working again.

@AlexxIT perhaps this ticket should be reopened for further investigation?

**Comment by AlexxIT** [comment] 2022-12-20 10:21
@lazmo88 do you have problem only with this sensor or with all cloud sensors?

**Comment by nicolacampagnolo** [comment] 2022-12-28 19:30
> @lazmo88 do you have problem only with this sensor or with all cloud sensors?

I have problem only with this sensor. Other sensors work well

**Comment by LukeRabauke** [comment] 2024-01-11 13:13
I have the exact same problem with DW2. Reloading the integration solves it for now.
How can the root cause be fixed? Any idea?
