### ISSUE TITLE
Malfunction after core_2024.1.0 update

### ISSUE THREAD

**Issue by ivanleovitanza** [AlexxIT/SonoffLAN#1292] opened 2024-01-04 09:21 UTC
hi,
after core_2024.1.0 update the integration does not update sonoff states, but the current measurements work

**Comment by Rikus102** [comment] 2024-01-04 09:26
I'm having the same issue.

**Comment by hmmbob** [comment] 2024-01-04 09:49
Duplicate of #1288, please close this issue and track #1288

**Comment by VaughanGerson** [comment] 2024-01-04 09:52
Same issue with my POWR320D, after latest core update no measurement data is available, also the device is no longer in the debug log

**Comment by cheehueisutd** [comment] 2024-01-04 10:49
Yes. I am facing the same issue. Please help. Thank you so much.

**Comment by hmmbob** [comment] 2024-01-04 10:55
People, stop posting here and head over to #1288

**Comment by cheehueisutd** [comment] 2024-01-04 11:02
There is a fix in #1288. Thank you!

**Closed** 2024-01-04 11:06 UTC
