### ISSUE TITLE
Sonoff ifan03 - Home Assistant 2022.2 - speed control not working

### ISSUE THREAD

**Issue by MJWMJW2** [AlexxIT/SonoffLAN#699] opened 2022-02-03 15:35 UTC
Sonoff LAN 2.4.6
Sonoff ifan03 fw 3.5.0
Home Assistant core-2022.2.0

Updating to latest version of Home Assistant core 2022.2.0 speed control no longer works - gives an error like unable to call. On and off works.

Reverted Core version and speed control works again. 

Unsure if this needs some local config change, or sonoffLAN update.  Any ideas?

Can upgrade again if logs required.

Breaking change listed on Home Assistant 
This is more a breaking change for custom integration developers.

Now that all core fans are using the new fan entity model, the compatibility shim has been removed. Custom integrations that have not yet switched to the new fan model may be affected. For more information see:

https://developers.home-assistant.io/docs/core/entity/fan/#deprecated-properties

Preset modes and percentages will continue to be translated back to legacy speeds until 2022.3 in order to give users a bit more time to update automations.

**Comment by GuidoKJ** [comment] 2022-02-04 04:59
Hi to all,

I can confirm this is also happening to me.

![image](https://user-images.githubusercontent.com/64809362/152474450-13d90dc6-b3e4-46e5-b527-4bd36bfe118d.png)

Here are some logs:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/fan/__init__.py:240
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:58:22 AM (18 occurrences)
Last logged: 1:56:36 AM

[140002229274128]
[140001793624432]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 921, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 246, in async_set_percentage
    await self.hass.async_add_executor_job(self.set_percentage, percentage)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 240, in set_percentage
    raise NotImplementedError()
NotImplementedError

Let me know if any other information is needed.

Cheers!

**Comment by bdraco** [comment] 2022-02-06 20:04
https://github.com/AlexxIT/SonoffLAN/issues/621

**Comment by RaidersPlay** [comment] 2022-02-07 11:04
I see this is now flagged as a enhancement rather than a bug or something similar.
This is a feature that was working and stopped working recently. It is not something that needs to be added but rather fixed.
I have a few Sonoff fans and all of them lost this ability. Suspect it is to do with the Home Assistant update.

ps... The Ewelink app is working. To switch over to it, would be a lot of work due to all the automation on my system. I would rather stay with this app if possible.

**Comment by stagea09** [comment] 2022-02-09 11:22
Also can confirm this with ifan03 units.
Using the service fan: set speed and using the values of low, medium or high work fine. 
Using the GUI interface on the entity it doesn't work as it gets to use the set percentage service. As stated above this upsets automations aswell as it changed from setting speed using values of low, med etc to percentages and now back...
I use openhasp panels and this will require yaml reconfigure to fix.

**Comment by ronjtaylor** [comment] 2022-02-19 20:36
https://developers.home-assistant.io/docs/core/entity/fan/#deprecated-properties
This is from Release notes on HA Blog

**Comment by Qoheleth** [comment] 2022-03-17 22:54
To make the situation even more odd, I have automations which set the fan speed using the now depreciated fan.set_speed service. They work. However, through the UI, using the slider to set the speed, (which uses fan.set_percentage, the current and preferred method), I get the "Failed to call service fan/set_percentage." The slider in the UI no longer shows the current speed as well.

**Comment by pakshuang** [comment] 2022-03-23 09:10
I am also experiencing the same issue with the percentage slider instead of discrete fan speeds. Manually setting the state in dev tools `speed: low` or any of the speeds listed in `speed_list` will not change the fan speed. Turning the fan on and off still works and it will turn on to the speed it was at before it was turned off. Should this issue be labelled as a bug instead of an enhancement?

**Comment by AlexxIT** [comment] 2022-04-19 15:43
Fixed in latest release

**Closed by AlexxIT** 2022-04-19 15:43 UTC
Labels: enhancement
