### ISSUE TITLE
eWelink Thermostat - cannot set target temperature from HA

### ISSUE THREAD

**Issue by diwit** [AlexxIT/SonoffLAN#358] opened 2021-01-22 22:05 UTC
Hi,

I just got  thermostat that works with eWeLink for my heating.

I can set it up in HA as a generic_thermostat, but the only thing it does it switch it on or off, I cannot actually set a target temperature and get it to update on the actual physical thermostat, so the heater won't start.

This is the one I got: https://ae04.alicdn.com/kf/U8998b5f708dd441f921abbb65f3542085.jpg
It has an AltoBeam chip apparently.

Is there any chance to get this working from HA? I am available to test things for you if you need any help with anything.

Thanks,

**Comment by rozza-m** [comment] 2021-01-29 18:54
Duplicate of #311 ?

**Comment by bwp91** [comment] 2021-03-03 07:54
If this helps:

uiid: 127

`params` object:

```json
{
      "volatility": 1, 
      "targetTemp": 20,
      "workMode": 1,
      "switch": "on",
      "temperature": 29,
      "fault": 0,
      "workState": 2,
      "tempScale": "c",
      "childLock": "off",
      "mon": "016800c801e0009602b20096032a009603fc00dc05280096",
      "tues": "016800c801e0009602b20096032a009603fc00dc05280096",
      "wed": "016800c801e0009602b20096032a009603fc00dc05280096",
      "thur": "016800c801e0009602b20096032a009603fc00dc05280096",
      "fri": "016800c801e0009602b20096032a009603fc00dc05280096",
      "sat": "016800c801e000c802b200c8032a00c803fc00c805280096",
      "sun": "016800c801e000c802b200c8032a00c803fc00c805280096"
}
```

* `workMode`:  1=manual, 2=programmed 3=economical
* `targetTemp`: between 5 and 45 celsius (not sure the values for fahrenheit) but needs to be to 0.5 degree
* `temperature`: sent in celsius or fahrenheit, to a 0.5 degree
* `workState`: 1=heating, 2=auto

I don't personally own this device but had access to one a while back.

Perhaps this could help!

**Comment by AlexxIT** [comment] 2022-05-02 06:17
Thanks to @bwp91 , added to latest master-version

**Closed by AlexxIT** 2022-05-02 06:17 UTC
Labels: enhancement
