### ISSUE TITLE
Seems like some methods will be deprecated soon in Home Assistant

### ISSUE THREAD

**Issue by ZainAjam** [AlexxIT/SonoffLAN#900] opened 2022-07-07 17:55 UTC
![Screenshot 2022-07-07 195354](https://user-images.githubusercontent.com/32865278/177838442-cec6cdd4-f0f2-448b-9830-21a4f9c02058.png)
![Screenshot 2022-07-07 195341](https://user-images.githubusercontent.com/32865278/177838452-e4ba880e-0ac1-4ee4-8fea-a0e87ddcdb6f.png)

**Comment by hmmbob** [comment] 2022-07-07 19:48
Duplicate of #897 , you can close this one

**Closed** 2022-07-07 20:37 UTC
