### ISSUE TITLE
Integration stops working after a period of time.

### ISSUE THREAD

**Issue by Joerybehousing** [AlexxIT/SonoffLAN#1125] opened 2023-02-28 09:16 UTC
Hello,
The integration randomly stops working and data not up to date anymore.
Doing a rboot of the integration, fixes the issue for a short period.
The log is giving me 2 errors in cloud.py, line 333 and 59.

```
2023-02-27 14:17:36.128 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_1001693779_energy is taking over 10 seconds
2023-02-27 14:17:37.762 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1001690466', 'apikey': '**************', 'sequence': '1677503852006'}
2023-02-27 14:17:38.745 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-27 14:17:38.754 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-27 14:40:58.934 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10016903ca', 'apikey': '********', 'sequence': '1677505253008'}
2023-02-27 14:41:00.087 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_1001690466_energy is taking over 10 seconds
2023-02-27 14:41:01.856 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1001690466', 'apikey': '*************', 'sequence': '1677505256007'}
2023-02-27 15:55:18.568 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_10016936f0_energy is taking over 10 seconds
2023-02-27 15:55:18.583 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_1001690850_energy is taking over 10 seconds
2023-02-27 15:55:18.587 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_10016949d8_energy is taking over 10 seconds
2023-02-27 15:55:18.592 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_1001694a23_energy is taking over 10 seconds
2023-02-27 15:55:18.597 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_1001692aba_energy is taking over 10 seconds
2023-02-27 15:55:18.601 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_100169365e_energy is taking over 10 seconds
2023-02-27 15:55:18.605 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_1001691785_energy is taking over 10 seconds
2023-02-27 15:55:18.609 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_10016924d3_energy is taking over 10 seconds
2023-02-27 15:55:18.614 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_100169206b_energy is taking over 10 seconds
2023-02-27 15:55:18.618 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_10016937b2_energy is taking over 10 seconds
2023-02-27 15:55:18.622 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sonoff_1001691929_energy is taking over 10 seconds
```

**Comment by Joerybehousing** [comment] 2023-02-28 10:49
And again:
2023-02-28 11:42:23.167 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1001321643', 'apikey': '*********', 'sequence': '1677580938001'}
2023-02-28 11:42:26.381 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-28 11:42:26.386 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-28 11:42:26.401 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-28 11:42:26.409 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-28 11:42:26.418 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-28 11:42:26.425 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-28 11:42:26.438 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 333, in _process_ws_msg
    self._set_response(data["sequence"], data["error"])
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 59, in _set_response
    self._waiters[sequence].set_result(result)
asyncio.exceptions.InvalidStateError: invalid state
2023-02-28 11:42:26.449 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

**Comment by slumdlordshnay** [comment] 2023-02-28 22:10
Same here I can reload it but it fails within a few hours max. I setup an automation to reload it after it becomes unknown or unavailable. But this should only be a temp fix.

**Comment by Yonny24** [comment] 2023-03-01 16:10
I've been experiencing issues also for a week or so. Devices are not syncing with the actual sonoff device state. Random and only a reboot of HA sync them correctly again. I wake up in the morning and some of the exterior lights are showing as on but they are off and show as off on the ewlink app. 
Been working flawlessly last 2 years.

Hope there is a fix soon thanks

**Comment by Remali-Ls** [comment] 2023-03-05 05:26
Same  issue after the last update.

System:
Home Assistant 2023.3.1 
Supervisor 2023.01.1 
Operating System 7.5 
Frontend 20230302.0 - latest 
Sonoff lan 3.4.0

**Comment by falieris** [comment] 2023-03-05 13:35
Same issue here! I hope to have a response from developers.

**Comment by dtrop1** [comment] 2023-03-07 17:11
I am seeing this as well.  It might not take down all the integrations at once, I only have a few but they eventually become unavailable.

**Comment by Claudio1L** [comment] 2023-03-12 05:37
same here. Just reloaded ha to resync status. ewelink was working

**Comment by sator86** [comment] 2023-03-13 18:35
same here, I have to reload sonoff plugin to get it working again
any solution will be appreciate 
thank you

**Comment by thefunkygibbon** [comment] 2023-03-15 15:22
as of today after updating last night, i'm experiencing the "unavailable" multiple times a day (rather than it seemingly happening overnight sporadically before).   
this is driving me bonkers.  Happy to help in any troubleshooting to whoever is dev for this integration.  @AlexxIT ?

**Comment by chuk-a** [comment] 2023-03-20 04:06
Same problem.

**Comment by thefunkygibbon** [comment] 2023-03-27 09:01
hey all, a great workaround since this issue doesn't appear to be being worked on,  is to create an automation to monitor a sonoff device and restart the service automatically.  its not a perfect solution but hopefully it should make the devices work for "most" of the time. 
https://github.com/AlexxIT/SonoffLAN/issues/1138#issuecomment-1478580171

**Comment by david-bann** [comment] 2023-03-30 06:19
Same problem here - all Sonoff devices become unavailable one by one. It doesn't take very long after reloading the integration for them to all go offline again.

**Comment by AlexxIT** [comment] 2023-03-30 09:51
Looks like cloud servers can't response on energy request. Exception fixed in latest master version. Will be in the next release

**Comment by Claudio1L** [comment] 2023-03-30 10:27
HI Alex

Is it valid also for local devices? I have to be rollback to have a stable release. All my son off are local. Thanks

**Comment by AlexxIT** [comment] 2023-03-30 10:38
@Claudio1L have you show logs with your problem?

**Comment by Claudio1L** [comment] 2023-03-31 05:07
No, i rebooted couple of times after two events, before understanding was
an integration issue. Then I quickly rolled back.
I can try again to get logs. The problem is that I don’t know when the
issue start. If I’m not at home could be an issue
Claudio
Il giorno gio 30 mar 2023 alle 12:38 Alex X ***@***.***> ha
scritto:

**Closed** 2023-03-31 11:15 UTC
Labels: bug
