### ISSUE TITLE
sonoff.number::XPulseWidth is overriding deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by xilicau** [AlexxIT/SonoffLAN#914] opened 2022-07-21 13:32 UTC
Hi,

in case you are not aware, it seems this plugin is using some soon-to-be-deprecated methods.

This is the warning message I am getting in the logs:

> 2022-07-21 13:59:28 WARNING (MainThread) [homeassistant.components.number] custom_components.sonoff.number::XPulseWidth is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

Thanks,
xilicau

**Comment by JackTalisker** [comment] 2022-07-21 14:38
duplicate of #897

**Closed** 2022-07-21 14:47 UTC
