### ISSUE TITLE
After 2024.1 bulb B05-BL controls no longer available.

### ISSUE THREAD

**Issue by ernstvanzyl** [AlexxIT/SonoffLAN#1290] opened 2024-01-04 07:00 UTC
"This entity is no longer being provided by the sonoff integration. If the entity is no longer in use, delete it in settings."
Entity light.sonoff_10014a3d8a
I can no longer automate turning the bulb on or off.
![Screenshot 2024-01-04 085859](https://github.com/AlexxIT/SonoffLAN/assets/35259551/ccb77d93-40ae-4ad4-a535-f317f91ad669)

**Comment by hmmbob** [comment] 2024-01-04 07:04
Duplicate of #1285 and #1288, please close this and add info in one of those

**Comment by hmmbob** [comment] 2024-01-04 08:23
I just posted an easy fix for this issue (state is wrong while component loads correctly) in #1288.

**Comment by hothome18** [comment] 2024-01-04 08:47
Yip, same here

**Comment by AlexxIT** [comment] 2024-01-04 18:42
#1285

**Closed by AlexxIT** 2024-01-04 18:42 UTC
Labels: duplicate
