### ISSUE TITLE
error

### ISSUE THREAD

**Issue by teygeo** [AlexxIT/SonoffLAN#891] opened 2022-07-06 10:29 UTC
![1657103281896](https://user-images.githubusercontent.com/81954558/177530285-62a64c99-aa60-427a-8559-9b31591162ee.jpg)

**Comment by djk314** [comment] 2022-07-06 10:37
same....

**Comment by drthanwho** [comment] 2022-07-06 10:40
Duplicate of #887

**Comment by tomadan1968** [comment] 2022-07-06 10:47
Me too the same problem...

**Comment by simeon-simsoft** [comment] 2022-07-06 10:49
me too.. happening here also

**Comment by peregrines2** [comment] 2022-07-06 10:58
Here too, very annoying problem :(

**Comment by drthanwho** [comment] 2022-07-06 10:59
@teygeo preferably close this issue and keep an eye on the other one instead as people now still comment here.

**Comment by teygeo** [comment] 2022-07-06 11:22
Goto https://github.com/AlexxIT/SonoffLAN/issues/887

**Closed** 2022-07-06 11:21 UTC
