### ISSUE TITLE
'EWeLinkToggle' object has no attribute 'async_turn_on_compat'

### ISSUE THREAD

**Issue by evaliukonis** [AlexxIT/SonoffLAN#409] opened 2021-03-03 21:02 UTC
Not working fan turn on calling service on Home Assistant 2021.3.0
turn_on - not working
turn_off - working
toggle - working

**Comment by VoyteckPL** [comment] 2021-03-04 08:29
I can confirm that error.

**Comment by TTLucian** [comment] 2021-03-05 18:32
Same here. Same error message.

**Comment by azbix** [comment] 2021-03-05 18:43
Same for me

**Comment by MarekSax** [comment] 2021-03-07 18:18
Same problem here. It's strange because I have 5 sonoff minis and only one have this problem.

**Comment by pablorlopes** [comment] 2021-03-09 00:45
Same here

**Comment by pablorlopes** [comment] 2021-03-09 22:29
I updated fan.py and it worked perfectly. Thank you so much! :)

**Comment by VoyteckPL** [comment] 2021-03-10 06:14
> I updated fan.py and it worked perfectly. Thank you so much! :)

I did the same and it works! Thanks!

**Comment by AlexxIT** [comment] 2021-03-10 18:56
Fixed in latest release

**Closed by AlexxIT** 2021-03-10 18:56 UTC
Labels: bug
