### ISSUE TITLE
HA builtin energy usage

### ISSUE THREAD

**Issue by guciopl** [AlexxIT/SonoffLAN#562] opened 2021-08-04 18:56 UTC
Hi,
With HA 2021.8 they implemented energy usage tools, but I cannot link usage from my sonoff POWs devices as they dont appear on the list. In help there is tip to inform integration author about this: https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics
Is there anything You can do here?

**Comment by johnjoemorgan** [comment] 2021-08-05 08:22
I can confirm the same with a S31.  I have one unit flashed with Tasmota that is reporting the power data to the Energy integration and on with Sonoff firmware that is not.

 I know that in of itself is of little help but please let me know what information or set up/configs you may want me to test out.

My timezone is GMT-8

**Comment by yousaf465** [comment] 2021-08-05 19:42
I am also looking for the same. Monitor energy usage using sonoff firmware.

**Comment by smartDev22** [comment] 2021-08-10 18:12
https://aliexpress.ru/item/4001119010843.html
I have such a relay, it does not have a built-in calculation of the consumed energy, how can I get this data from this device? Mb there is some description of api from ewelink?

**Comment by johnjoemorgan** [comment] 2021-08-11 04:25
@yousaf465 @smartDev22 

You need to create a sensor in HA via a template.

In your sensor.yaml create the sensor from the Sonoff device:

  - platform: integration
    source: sensor.sonoff_10003cc37b_power
    name: IT Power Manual
    unit_prefix: k
    unit: kWh
    round: 2

That creates a kWh sensor you can either place into the UI as usual and/or the new Energy dashboard.

Devices such as these Sonoff's maybe updated via firmware updates later to show the information to HA in the way HA wants but it's unlikely

![image 1](https://user-images.githubusercontent.com/45795798/128969269-e92e7784-a183-4664-ba77-9c2d346946e7.jpg)
![image 2](https://user-images.githubusercontent.com/45795798/128969296-bd67e38e-9b83-4c1b-b945-dd0cba8b1345.jpg)


Additionally, if your device only gives the Watts or Load Power or Power as an **_attribute_** then you can use this code in sensor.yaml to make that attribute into a sensor for Watts/Power then then use the code above.

  - platform: template
    sensors:
      water_filter_watts:
        device_class: power
        unit_of_measurement: 'W'
        friendly_name: 'Water Filter Watts'
        value_template: "{{ states.switch.xiaomi_miio_switch.attributes.load_power }}"

**Comment by guciopl** [comment] 2021-08-11 08:51
@johnjoemorgan  
I have done what You wrote:

```
sensor:
- platform: integration
  source: sensor.sonoff_10007c87fb_power
  name: Dishwasher
  unit_prefix: k
  unit: kWh
  round: 2

- platform: template
  sensors:
    power_dishwasher:
      friendly_name: DIshwasher
      unit_of_measurement: W
      device_class: power
      value_template: "{{ state_attr('switch.sonoff_10007c87fb', 'power') }}"
```

and still no statistics available in step 3 of energy dashboard.
![ha](https://user-images.githubusercontent.com/61185430/128999568-39cfccb8-4f3c-46de-89f9-054af6a42d3c.PNG)

**Comment by Gferretta** [comment] 2021-08-11 11:44
> @johnjoemorgan  
> I have done what You wrote:
> 
> ```
> sensor:
> - platform: integration
>   source: sensor.sonoff_10007c87fb_power
>   name: Dishwasher
>   unit_prefix: k
>   unit: kWh
>   round: 2
> 
> - platform: template
>   sensors:
>     power_dishwasher:
>       friendly_name: Dishwasher
>       unit_of_measurement: W
>       device_class: power
>       value_template: "{{ state_attr('switch.sonoff_10007c87fb', 'power') }}"
> ```
> 
> and still no statistics available in step 3 of energy dashboard.
> ![ha](https://user-images.githubusercontent.com/61185430/128999568-39cfccb8-4f3c-46de-89f9-054af6a42d3c.PNG)
> 

Add:
state_class: measurement

**Comment by johnjoemorgan** [comment] 2021-08-11 14:05
@Gferretta it can take up to an hour for data

End of the day here fir me (UTC-8) Will compare you code asap

**Comment by guciopl** [comment] 2021-08-11 14:13
Added       state_class: measurement

```
sensor:
- platform: integration
  source: sensor.sonoff_10007c87fb_power
  name: Dishwasher
  unit_prefix: k
  unit: kWh
  round: 2

- platform: template
  sensors:
    power_dishwasher:
      friendly_name: Dishwasher
      unit_of_measurement: W
      device_class: power
      state_class: measurement
      value_template: "{{ state_attr('switch.sonoff_10007c87fb', 'power') }}"

```

Now in HA > Settings > Server configuration > Check configuration I have:
Invalid config for [sensor.template]: [state_class] is an invalid option for [sensor.template]. Check: sensor.template->sensors->power_pralka->state_class. (See ?, line ?).

**Comment by yousaf465** [comment] 2021-08-11 14:14
since I have created a energy sensor before hand, all I had to do was change the entity type. https://community.home-assistant.io/t/integration-solar-inverter-huawei-2000l/132350/589?u=yousaf465 
`Thanks for the tip. I was able to add Sonoff Pow2 using Alexxit’s SonoffLan control to Energy dashboard. GitHub - AlexxIT/SonoffLAN: Control Sonoff Devices with eWeLink (original) firmware over LAN and/or Cloud from Home Assistant 2
Steps are simple

configuration
Scroll down to Customizations
select your entity
select device class as “energy”
select state class as " measurement"
Select other
Attribute name “last_reset”.
8 attribute value “1970-01-01T00:00:00+00:00”
click save
Now your sensor will show up in energy dashboard.`

**Comment by johnjoemorgan** [comment] 2021-08-12 10:26
@guciopl Here's the first part of my sensor.yaml

'
# Date Time
  - platform: websocket_api
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: template
    sensors:
      water_filter_watts:
        device_class: power
        unit_of_measurement: 'W'
        friendly_name: 'Water Filter Watts'
        value_template: "{{ states.switch.xiaomi_miio_switch.attributes.load_power }}"


  - platform: integration
    source: sensor.tyxxxxxxxxxxxxxde_2
    name: Desk Power Manual
    unit_prefix: k
    unit: kWh
    round: 2
  - platform: integration
    source: sensor.sonoff_10003cc37b_power
    name: IT Power Manual
    unit_prefix: k
    unit: kWh
'

:-) Maybe the order in which the "software" sensors appear in the file makes a difference.  My template appears before the integration??????????

**Comment by guciopl** [comment] 2021-08-12 12:55
I dont understand Your code, I dont see those sensors to be linked by no means.
In my code both sensors are linked to same device, in Yours we have 3 devices.

Anyway I managed to create software sensors which are visible in HA energy tab, however they are all empty, no power usage is transfered from hardware sensors to software sensors.

**Comment by johnjoemorgan** [comment] 2021-08-13 04:01
@guciopl  Sorry I may have over complicated things in my example.

For my Sonoff devices the only code is in sensor.yaml:

  - platform: integration
    source: sensor.SONOFF-ENTITY_POWER
    name: NEW ENTITY FOR ENERGY
    unit_prefix: k
    unit: kWh
    round: 2


You can find your sensor.SONOFF-ENTITY_POWER from your entities list and replace the one above.

After checking your config and restarting you should see a new sensor "NEW ENTITY FOR ENERGY" or whatever you have nemaed it.

This is the entity you can add to the energy dashboard or anywhere in the HA UI.

Note it may take up to an hour for any data to show in the new entity.  So please be patient :-)

Hope this help and sorry for the confusion.

**Comment by guciopl** [comment] 2021-08-13 07:33
Well I don't have S31, I have POWs R2 only, but added it to sensor.yaml same as You wrote:
![image](https://user-images.githubusercontent.com/61185430/129320999-ce815ff4-7409-44ec-9e43-71be4ee7ad75.png)

and no sensor in energy tab:
![image](https://user-images.githubusercontent.com/61185430/129321266-712f9051-8df0-45e2-9ae0-f692eaeddc3f.png)

**Comment by yousaf465** [comment] 2021-08-13 07:41
> Well I don't have S31, I have POWs R2 only, but added it to sensor.yaml same as You wrote:
> ![image](https://user-images.githubusercontent.com/61185430/129320999-ce815ff4-7409-44ec-9e43-71be4ee7ad75.png)
> 
> and no sensor in energy tab:
> ![image](https://user-images.githubusercontent.com/61185430/129321266-712f9051-8df0-45e2-9ae0-f692eaeddc3f.png)

you have to change the state class and device class too along with last reset attribute value.

**Comment by guciopl** [comment] 2021-08-13 08:14
> you have to change the state class and device class too along with last reset attribute value.
those entiry doesnt take that attributes
![image](https://user-images.githubusercontent.com/61185430/129325087-54945300-9aa8-400f-8421-642bd7266453.png)
![image](https://user-images.githubusercontent.com/61185430/129325174-e55743c6-af2d-45d6-a947-d0609d9ea615.png)

I moved sensors back from sensor.yaml to configuration.yaml and now they are possible to pick in energy tab but not populating anything, will wait some time
![image](https://user-images.githubusercontent.com/61185430/129326154-be2a641a-0eef-48a9-8a11-2ca43c4d220b.png)

**Comment by AlexxIT** [comment] 2022-04-24 06:40
Added energy sensor for pow devices in latest master-version. Will be in next release.
Data loaded from the cloud every hour.

**Closed by AlexxIT** 2022-04-24 06:40 UTC
Labels: enhancement

**Comment by coolspot18** [comment] 2022-10-28 21:54
Is it beneficial to assign a unique id to energy sensors? I noticed when I do - it shows up in the Entities list as "[Riemann sum integral](https://www.home-assistant.io/integrations/integration/)" rather than just "Sensor"?

**Comment by msavazzi** [comment] 2026-08-20 16:38
> since I had created an energy sensor beforehand, all I had to do was change the entity type. https://community.home-assistant.io/t/integration-solar-inverter-huawei-2000l/132350/589?u=yousaf465 `Thanks for the tip. I was able to add Sonoff Pow2 using Alexxit’s SonoffLan control to Energy dashboard. GitHub - AlexxIT/SonoffLAN: Control Sonoff Devices with eWeLink (original) firmware over LAN and/or Cloud from Home Assistant 2 Steps are simple
> 
> configuration Scroll down to Customizations select your entity select device class as “energy” select state class as " measurement" Select other Attribute name “last_reset”. 8 attribute value “1970-01-01T00:00:00+00:00” click save Now your sensor will show up in energy dashboard.` Yes I am using single sensor to test solar, grid and consumption ![image](https://user-images.githubusercontent.com/83491212/129045534-895c4c6d-69e7-4f48-99f7-59f5cbc51ca8.png) ![image](https://user-images.githubusercontent.com/83491212/129045557-d1db6c57-e4a0-41af-83b0-4a4cce79f20f.png) ![image](https://user-images.githubusercontent.com/83491212/129045793-755321f8-3e2e-4609-aa81-1e01f3746347.png) ![image](https://user-images.githubusercontent.com/83491212/129045992-3903f0e5-3d8f-44b3-80ff-3d6542739a98.png)

Can you explain us what it means: 
Configuration 
Scroll down to Customizations 

Where? on the UI? where can I find it?
