### ISSUE TITLE
Plugin requires reconfiguration

### ISSUE THREAD

**Issue by pabutterworth** [AlexxIT/SonoffLAN#841] opened 2022-05-15 15:01 UTC
Hi, 
I have been using the integration successfully for some time, its great.

It now claims it needs reconfiguration on the integrations page, but if I attempt reconfiguration it says it's already configured. How can I remove the warning?
Thanks in advance.
<img width="290" alt="Screenshot 2022-05-15 at 16 00 01" src="https://user-images.githubusercontent.com/16760791/168479515-694eeb96-b25b-4986-b0f1-13ce95683822.png">
<img width="399" alt="Screenshot 2022-05-15 at 16 01 28" src="https://user-images.githubusercontent.com/16760791/168479580-ba00fb77-139d-4810-ba47-262b8bd82ca9.png">

**Comment by smith844** [comment] 2022-07-02 07:23
I have the same issue, any ideas how to fix it ?

**Comment by VictoriousCupid** [comment] 2022-07-06 06:48
same issue here

**Comment by VonOx** [comment] 2022-07-06 12:39
@pabutterworth Hi, did you find solution ?

**Comment by VimalO** [comment] 2022-07-06 19:44
Same issue here. 
Any resolution for this?

**Comment by tduzzi** [comment] 2022-07-07 11:22
Same issue for me.  Any suggestions?

**Comment by paulius2k** [comment] 2022-07-07 14:01
I have the same issue after upgrading Home Assistant Core to 2022.7.0

**Comment by rdndnl** [comment] 2022-07-07 14:12
I had the same issue, resolved with the following procedure:

- Removed Sonoff integration
- Reboot HA
- Added Sonoff integration, when requested in the popup:
   - in the email input field insert a different email
   - leave the password empty
- The integration will be added with 2 account, the older and the new (fake) one. Remove the new (fake) and the integration will work ok as before.

**Comment by AlexxIT** [comment] 2022-07-07 14:15
Please check latest release v3.1.0

**Comment by rdndnl** [comment] 2022-07-07 14:19
Done, the integration was already upgraded to release v3.1.0, I had to follow the procedure above.

**Comment by paulius2k** [comment] 2022-07-07 18:37
Not exactly sure what solved the issue for me:
- I removed the integration as per @rdndnl's recommendation,
- I ALSO loged-out from the eWeLink app on my phone (had forgotten that previously),
- after restarting HASS, I have my Sonoff integration working fine and no more message to "reconfigure" and I did not have to do the rest of @rdndnl's actions.

**Comment by VimalO** [comment] 2022-07-08 13:21
> Same issue here. Any resolution for this?

I have upgraded to 2022.7.0 and SOnoff 3.1.0
While most of my devices have now reappeared, I have a few devices which were working previously and which are now unavailable although they are available in the ewelink app.
Also, I couldnt find the documentation on how to enable multiple homes in the configuration

**Comment by AlexxIT** [comment] 2023-03-31 10:32
Can't reproduce problem on latest integration version.
Please reopen the issue if there are still any problems.

**Closed by AlexxIT** 2023-03-31 10:32 UTC
Labels: question
