### ISSUE TITLE
Problems with zeroconf implementation (local mode)

### ISSUE THREAD

**Issue by MJWMJW2** [AlexxIT/SonoffLAN#839] opened 2022-05-14 14:45 UTC
Sonoff Micro (USB switch).
Was working fine with internet blocked for device.   No longer works this way - internet port has to be unblocked to work.  Only works with Cloud control, not local.  If using auto it will only use cloud control.

I do not know how to view the logs for this integration (sorry!)

**Comment by AlexxIT** [comment] 2022-05-14 15:24
https://github.com/AlexxIT/SonoffLAN#issues

**Comment by MJWMJW2** [comment] 2022-05-14 22:38
Thank you - it took me some time to find the debug location, with the new menus.

I think this may be the important part.  "Can't find key in zeroconf cache: ewelink_100126d38a.local."

```
2022-05-14 23:34:46 [D] 3 devices loaded from Cloud
2022-05-14 23:34:46 [D] 100126d38a UIID 0077 | {'version': 8, 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'senMode': {'enabled': 0, 'dTime': 10, 'tUnit': 's', 'outlets': [0, 1, 2, 3], 'effectives': [{'outlet': 0, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 1, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 2, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}, {'outlet': 3, 'enabled': 0, 'days': [0, 1, 2, 3, 4, 5, 6], 'effIndex': [{'index': 0, 'enabled': 1, 'from': '00:00', 'to': '23:59'}, {'index': 1, 'enabled': 0, 'from': '00:00', 'to': '23:59'}]}]}, 'savMode': {'enabled': 0, 'dTime': 1, 'tUnit': 'm', 'outlets': [0, 1, 2, 3]}, 'alertMode': {'enabled': 0}, 'lock': 0, 'sledOnline': 'on', 'rssi': -62, 'fwVersion': '3.7.1', 'selfApikey': '123'}
2022-05-14 23:34:46 [D] 1000d4ba6d UIID 0077 | {'version': 8, 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 2500, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'lock': 0, 'sledOnline': 'on', 'rssi': -49, 'fwVersion': '3.4.0', 'selfApikey': '123'}
2022-05-14 23:34:46 [D] 1000cc26dc UIID 0034 | {'configure': [{'startup': 'on', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'stay', 'outlet': 2}, {'startup': 'stay', 'outlet': 3}], 'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'on', 'outlet': 3}], 'rssi': -46, 'fwVersion': '3.5.0', 'init': 1, 'sledOnline': 'on', 'version': 8, 'only_device': {'ota': 'success'}}
2022-05-14 23:34:46 [D] Can't find key in zeroconf cache: ewelink_100126d38a.local.
2022-05-14 23:34:46 [D] Can't find key in zeroconf cache: ewelink_1000d4ba6d.local.
```

**Comment by AlexxIT** [comment] 2022-05-15 05:23
I think I need to get Sonoff Micro locally for tests. I don't have it right now.

**Comment by MJWMJW2** [comment] 2022-05-15 13:00
I think it may be hard for me to get a device shipped to you - but if you have some idea how I could help you to get one, please inform me.

**Comment by AlexxIT** [comment] 2022-05-15 15:23
I have one with 200km from me and can't test it locally :)

**Comment by birdwing** [comment] 2022-06-19 13:22
I am having a similar issue with my Sonoff Micro.
In local only, sending on/off commands will trigger the device to turn on/off, but home assistant will not update the sensor to reflect the new state.
In auto mode it works because the new state is retrieved from the cloud.

Here is the debug of me switching the device on then back off:
```
2022-06-19 08:57:21 [D] 100149d906 => Local4 | {'switches': [{'outlet': 0, 'switch': 'on'}]} <= {'sequence': '1655643441000', 'seq': 45, 'error': 0}
2022-06-19 08:57:21 [D] Can't find address for eWeLink_100149d906._ewelink._tcp.local.
2022-06-19 08:57:21 [D] 100149d906 <= Cloud3 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'selfApikey': '123'} | None
2022-06-19 08:57:21 [D] 100149d906 <= Cloud3 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}]} | None
2022-06-19 08:57:22 [D] Can't find address for eWeLink_100149d906._ewelink._tcp.local.
2022-06-19 08:57:22 [D] 100149d906 => Local4 | {'switches': [{'outlet': 0, 'switch': 'off'}]} <= {'sequence': '1655643442000', 'seq': 47, 'error': 0}
2022-06-19 08:57:22 [D] 100149d906 <= Cloud3 | {'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'selfApikey': '123'} | None
2022-06-19 08:57:22 [D] 100149d906 <= Cloud3 | {'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}]} | None
2022-06-19 08:57:23 [D] Can't find address for eWeLink_100149d906._ewelink._tcp.local.
```
I have a seperate linux box running on my network with mdns-scan
When I run the scan I can see both my Home assistant instance and the Sonoff Mini listed:
```
me@debian:~# sudo mdns-scan
+ homeassistant [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]._workstation._tcp.local
+ DD-WRT [xx:xx:xx:xx:xx:xx]._workstation._tcp.local
+ eWeLink_100149d906._ewelink._tcp.local
+ The Browns._home-assistant._tcp.local
```
I did notice something strange though.
While mdns-scan is running, even the cloud service fails to work, and the device is reported as offline.

```
2022-06-19 09:16:08 [D] 100149d906 => Cloud4 | {'switches': [{'outlet': 0, 'switch': 'off'}]} | 1655644xxxxxx
2022-06-19 09:16:12 [W] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '100149d906', 'apikey': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'sequence': '1655644xxxxxx'}
2022-06-19 09:16:13 [W] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '100149d906', 'apikey': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'sequence': '1655644xxxxxx'}
2022-06-19 09:16:17 [D] 100149d906 <= Cloud3 | {'online': False} | None
2022-06-19 09:16:18 [D] 100149d906 => Local4 | {'cmd': 'info'} !! Can't connect: Cannot connect to host 10.0.0.xxx:8081 ssl:default [Connect call failed ('10.0.0.xxx', 8081)]
2022-06-19 09:16:18 [D] 100149d906 !! Local4 | Device offline
```

**Comment by birdwing** [comment] 2022-06-22 01:23
I just noticed something strange today while debugging mDNS on my network (to make sure the issue wasn't with me)

If I enable "local mode" I get this:
```
2022-06-21 21:10:48 [D] LOCAL mode start
2022-06-21 21:10:48 [D] 100149d906 <= Local3 | {'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'stay', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'rssi': -53, 'senMode': {'enabled': 0, 'dTime': 10, 'tUnit': 's', 'outlets': [0, 1, 2, 3]}, 'savMode': {'enabled': 0, 'dTime': 1, 'tUnit': 'm', 'outlets': [0, 1, 2, 3]}, 'alertMode': {'enabled': 0}} | 39
2022-06-21 21:10:56 [D] 100149d906 => Local4 | {'switches': [{'outlet': 0, 'switch': 'on'}]} <= {'sequence': '1655860256000', 'seq': 40, 'error': 0}
2022-06-21 21:10:56 [D] Can't find address for eWeLink_100149d906._ewelink._tcp.local.
2022-06-21 21:10:57 [D] Can't find address for eWeLink_100149d906._ewelink._tcp.local.
2022-06-21 21:10:58 [D] 100149d906 => Local4 | {'switches': [{'outlet': 0, 'switch': 'off'}]} <= {'sequence': '1655860258000', 'seq': 42, 'error': 0}
2022-06-21 21:10:58 [D] Can't find address for eWeLink_100149d906._ewelink._tcp.local.
2022-06-21 21:11:00 [D] Can't find address for eWeLink_100149d906._ewelink._tcp.local.
```
As you can see from line 2, the integration manages to find and pull down data from the device 1 time. Then it continues to fail afterwards.

This same thing happens with "auto mode":
```
2022-06-21 21:09:28 [D] AUTO mode start
2022-06-21 21:09:28 [D] 100149d906 <= Local3 | {'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'stay', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'rssi': -55, 'senMode': {'enabled': 0, 'dTime': 10, 'tUnit': 's', 'outlets': [0, 1, 2, 3]}, 'savMode': {'enabled': 0, 'dTime': 1, 'tUnit': 'm', 'outlets': [0, 1, 2, 3]}, 'alertMode': {'enabled': 0}} | 35
2022-06-21 21:09:29 [D] CLOUD False => True
2022-06-21 21:09:42 [D] 100149d906 => Local4 | {'switches': [{'outlet': 0, 'switch': 'on'}]} <= {'sequence': '1655860182000', 'seq': 36, 'error': 0}
2022-06-21 21:09:42 [D] Can't find address for eWeLink_100149d906._ewelink._tcp.local.
2022-06-21 21:09:42 [D] 100149d906 <= Cloud3 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'selfApikey': '123'} | None
```

I think the issue lies somewhere in core/ewelink/local.py in either async_update_records() or restore_from_cache().
Somehow the way the address is getting stored is different from how it is being retrieved from cache.

**Comment by birdwing** [comment] 2022-06-22 18:26
I modified the async_update_records() function in core/ewelink/local.py to log the {records} object at the beginning of the loop.

This is what I see when the integration first starts out:
```
[
	RecordUpdate(new=record[ptr,in,_ewelink._tcp.local.]=4500/4499,eWeLink_100149d906._ewelink._tcp.local., old=None),
	RecordUpdate(new=record[srv,in-unique,eWeLink_100149d906._ewelink._tcp.local.]=120/119,eWeLink_100149d906.local.:8081, old=None),
	RecordUpdate(new=record[txt,in-unique,eWeLink_100149d906._ewelink._tcp.local.]=4500/4499,b'\x8ddata4='..., old=None),
	RecordUpdate(new=record[a,in-unique,eWeLink_100149d906.local.]=120/119,10.0.0.136, old=None)
]
```
Everything functions as expected, a query goes out for the _ewelink._tcp service type and the a record is returned
However, after clicking the switch to update the device this is output:
```
[
	
	RecordUpdate(new=record[ptr,in,_services._dns-sd._udp.local.]=4500/4499,_ewelink._tcp.local., old=None), 
	RecordUpdate(new=record[ptr,in,_ewelink._tcp.local.]=4500/4499,eWeLink_100149d906._ewelink._tcp.local., old=record[ptr,in,_ewelink._tcp.local.]=4500/4499,eWeLink_100149d906._ewelink._tcp.local.), 
	RecordUpdate(new=record[srv,in-unique,eWeLink_100149d906._ewelink._tcp.local.]=120/119,eWeLink_100149d906.local.:8081, old=None), 
	RecordUpdate(new=record[txt,in-unique,eWeLink_100149d906._ewelink._tcp.local.]=4500/4499,b'\x8ddata4='..., old=None)
]
```

For some reason the service type gets switched back to the default _services._dns-sd._udp.local
Because of this no A records are returned for ewelink devices. So no host can be found.

**Comment by randysnel** [comment] 2022-06-23 14:58
Recently i observed the same behaviour. The thing I observed is that after a HA reboot the first 10-20 seconds the switches in HA work fine and update the corrosponding state.

**Comment by birdwing** [comment] 2022-06-23 15:24
I believe the issue is because the integration is attempting to use the IPaddress as the host in the message dispatcher. 
Rather than the FQDN of the device in my case: **eWeLink_100149d906.local**

The FQDN is available in both cases in the srv record
The ipAddress is only available in the A record which vanishes after the first run.

I may fork the repo and see if I can re-write the zeroconf configuration to use FQDN for host instead of Ipaddress.
I'm not even sure if using the FQDN for the message dispatchers will work nor not.

**Comment by birdwing** [comment] 2022-06-23 18:08
So, I have a possibly very stupid fix that seems to work for me. Your mileage may vary, as I only have a single sonoff device right now, and I am not sure if this would break anything else.

I re-wrote the async_update_records() and restore_from_cache() functions for the XServiceBrowser class found in the core/ewelink/local.py file

```python
    def async_update_records(self, zc, now: float, records: list) -> None:
        for record, old_record in records:
            try:
                # old_record - skip previous seen record
                # record.ttl <= 1 - skip previous (old) cached records
                # process only DNSText records with our suffix
                if old_record or record.ttl <= 1 or \
                        not isinstance(record, DNSText) or \
                        not record.key.endswith(self.suffix):
                    continue

                if not record.is_expired(now):
                    host = record.key.replace(self.suffix, '.local.')
                    data = self.decode_text(record.text)
                    asyncio.create_task(self.handler(record.name, host, data))
                else:
                    asyncio.create_task(self.handler(record.name))

            except Exception as e:
                _LOGGER.warning("Can't process zeroconf", exc_info=e)

        AsyncServiceBrowser.async_update_records(self, zc, now, records)

    def restore_from_cache(self):
        now = current_time_millis()
        cache: dict = self.zc.cache.cache
        for key, records in cache.items():
            try:
                if not key.endswith(self.suffix):
                    continue
                for record in records.keys():
                    if not isinstance(record, DNSText) or \
                            record.is_expired(now):
                        continue
                    
                    key = record.key.split(".", 1)[0] + ".local."
                    host = record.key.replace(self.suffix, '.local.')
                    data = self.decode_text(record.text)
                    asyncio.create_task(self.handler(record.name, host, data))

            except KeyError:
                _LOGGER.debug(f"Can't find key in zeroconf cache: {key}")
            except Exception as e:
                _LOGGER.warning("Can't restore zeroconf cache", exc_info=e)
```

This update completely ignores DNSAddress. It removes the loop that looked for A records, and instead _infers_ the FQDN of the sonoff device by removing the suffix from the key and replacing it with .local.

So for example, the suffix is **._ewelink._tcp.local.** and the key is **eWeLink_100149d906._ewelink._tcp.local.**
so ```host = record.key.replace(self.suffix, '.local.')```
resulting in: **eWeLink_100149d906.local.**

Doing this only affects the host, the _record.name_ passed to the handler is the same as before, and the data can still be parsed because it's still using the TXT record. From what I understand of mDNS removing the service type (suffix) should result in a correct and accurate FQDN.

Again, test with caution. The more appropriate fix would be to attempt to pull down both the TXT and SRV records and match them by the key. Then use the SRV record to get the "server_key" property, which is the FQDN, and the TXT record for the data. I however got lazy, and wanted to see if using the FQDN instead of the ip address was feasible.

**Comment by birdwing** [comment] 2022-06-24 19:38
Okay I solved my lazyness problem.
Here is a _slightly_ less stupid fix that works for me.
I basically did the "more appropriate fix" I mentioned above.
Again **your milleage may vary** I only have 1 sonoff device.

At the top of the core/ewelink/local.py file you will need to add DNSService
It's line 17:
```python
from zeroconf import Zeroconf, DNSText, DNSService, DNSAddress, current_time_millis
```

Here is the updated async_update_records() and restore_from_cache() functions for the XServiceBrowser class of that same file:
```python
    def async_update_records(self, zc, now: float, records: list) -> None:
        try:
            # Create dictionary to store matching TXT and SRV records by key
            foundRecords = {}
            for record, old_record in records:
                # old_record - skip previous seen txt record
                # record.ttl <= 1 - skip previous (old) cached records
                # process only DNSText or DNSService records with our suffix
                # Skip address records, we get the hostname from the srv record
                if (old_record and isinstance(record, DNSText)) or record.ttl <= 1 or \
                        not (isinstance(record, DNSText) or isinstance(record, DNSService)) or \
                        not record.key.endswith(self.suffix) or \
                        isinstance(record, DNSAddress):
                    continue

                # Insert empty dictionary into foundRecords for each record key encountered
                foundRecords.setdefault(record.key, {})
                # Store matching DNSService record
                if isinstance(record, DNSService):
                    foundRecords[record.key].setdefault('srv', record)
                # Store matching DNSText record
                if isinstance(record, DNSText):
                    foundRecords[record.key].setdefault('txt', record)

                # If both records have been found for a key
                if 'srv' in foundRecords[record.key] and 'txt' in foundRecords[record.key]:
                    found = foundRecords[record.key]
                    if not (found['srv'].is_expired(now) and found['txt'].is_expired(now)):
                        name = found['txt'].name
                        host = found['srv'].server_key
                        data = self.decode_text(found['txt'].text)
                        asyncio.create_task(self.handler(name, host, data))
                    else:
                        asyncio.create_task(self.handler(record.name))

        except Exception as e:
            _LOGGER.warning("Can't process zeroconf", exc_info=e)

        AsyncServiceBrowser.async_update_records(self, zc, now, records)

    def restore_from_cache(self):
        now = current_time_millis()
        cache: dict = self.zc.cache.cache
        try:
            # Create dictionary to store matching TXT and SRV records by key
            foundRecords = {}
            for key, records in cache.items():
                if not key.endswith(self.suffix):
                    continue
                for record in records.keys():
                    if not (isinstance(record, DNSText) or isinstance(record, DNSService)):
                        continue
                    # Insert empty dictionary into foundRecords for each record key encountered
                    foundRecords.setdefault(record.key, {})
                    # Store matching DNSService record
                    if isinstance(record, DNSService):
                        foundRecords[record.key].setdefault('srv', record)
                    # Store matching DNSText record
                    if isinstance(record, DNSText):
                        foundRecords[record.key].setdefault('txt', record)

                    # If both records have been found for a key
                    if 'srv' in foundRecords[record.key] and 'txt' in foundRecords[record.key]:
                        found = foundRecords[record.key]
                        if (found['srv'].is_expired(now) or found['txt'].is_expired(now)):
                            continue

                        key = record.key.split(".", 1)[0] + ".local."
                        name = found['txt'].name
                        host = found['srv'].server_key
                        data = self.decode_text(found['txt'].text)
                        asyncio.create_task(self.handler(name, host, data))

        except KeyError:
            _LOGGER.debug(f"Can't find key in zeroconf cache: {key}")
        except Exception as e:
            _LOGGER.warning("Can't restore zeroconf cache", exc_info=e)
```
This changes the functionality from using the devices IP address to using it's hostname.
While the function is looping through the records, it is storing only DNSText and DNSService records in a dictionary of dictionaries.
Effectively this groups the DNSText and DNSService record by their .key values.

When both the DNSText and DNSService record have been found with a matching key, it then pulls the hostname from the DNSService record (.server_key) and then gets the name and data from the matching DNSText record.

If requested I can fork the repository and submit a pull request, I just don't know from my limited testing if changing from IP to hostname would cause issues with other devices.

**Comment by Seemone** [comment] 2022-07-07 09:20
I suddenly started to have the same problem a few days ago. I tested the above patch to local.py and I can confirm it works for me as well. Thanks!

**Comment by omenek159** [comment] 2022-07-14 11:18
I can confirm that @birdwing modification works for me too.

**Comment by vanstolyarov** [comment] 2022-07-18 15:20
+1 to @birdwing fix. It solved problem with local mode with THR316D

**Comment by AlexxIT** [comment] 2022-07-26 14:30
@birdwing Thanks! You did a great job of finding the problem.

I don't think that using a local hostname is stable solution for all routers and network setups. It's better to find some combined solution. Using IP addresses as main, and using hostname as fallback.

But I'm not home for the next two weeks. I won't be able to write a solution.

@jeffallen Thanks! But you copied code with wrong indentation. It won't work.

**Comment by birdwing** [comment] 2022-07-27 01:57
@AlexxIT 
I somewhat disagree. Sonoff devices are designed to work with MDNS, and the entire point of MDNS is so you don't have to know the devices IP Address. Most devices can handle MDNS and local hostnames nowadays. That is how "Casting" works when you cast to a chromecast device or other similar device.

The reason I looked to switch to the hostname was because my Sonoff Micro was not broadcasting it's IP Address every time it gave an update. It only broadcast it's IP Address (A record on DNS) once about every hour from what I could tell. Every update in between that time failed and caused home assistant to mark the device as being "off" or "unavailable". 

I also think that some Sonoff devices don't broadcast their A record (ip address) at all, which is why some devices only work on "cloud" only mode. Switching to using hostnames might allow those devices to function locally. If people have issues with MDNS (local domains) not working on their network, chances are they will have a hard time with any local IOT device, and could switch into Auto or Cloud.

If you do want to keep the IP addresses, you would have to detect if an DNSAddress record exists, if so use IP address, if not use hostname, but from what I and others could tell the hostname was always available.

**Comment by AlexxIT** [comment] 2022-07-27 02:38
Oh. I've had dozens of issues about local control not working. A lot of users are using trash where the router is supposed to be.

I understand the problem with A recording on some devices. Thank you! I think it' s better to use the IP address for the devices that send it. And use hostname for devices that don't send it. Just need more tests when I get home.

**Comment by tannisroot** [comment] 2022-08-22 14:25
Sorry to bump this up like this, but is there an up-to-date workaround to this problem? I've tried rebasing the older pr by jeffallen, but the integration fails to install with that, and the version PR was made against can't sign in.

**Comment by 20bart** [comment] 2022-09-04 20:41
I just tried this and it also fixes my issue with the position of the cover not being updated which I mentioned in #917

However (not related I think), when the cover is opening and I "pause" it half way, I can't open it any further because the opening button gets disabled. (the same happens the other way around).

**Comment by cdemoulins** [comment] 2022-09-18 12:20
The patch from @birdwing fix my issue in local mode for my DUALR3 device.

Thanks

**Comment by AlexxIT** [comment] 2022-09-24 14:21
New fix already in master version. Will be in next release

**Comment by birdwing** [comment] 2022-09-24 17:02
As expected looks better written than my solution 🤪
Can't wait to try it out 😁
Thanks for the work on this project @AlexxIT

**Comment by tannisroot** [comment] 2022-09-24 18:01
I have an issue where if I set connection mode to "local" in configuration, my device (sonoff micro) becomes unavailable - despite it having no cloud connection (i had it disabled via a firewall rule). It works fine in "auto" mode though which seems to work by issuing local commands. Can anyone confirm this?

**Comment by tannisroot** [comment] 2022-09-24 18:01
That is with latest master of course.

**Comment by brentcohen** [comment] 2022-09-28 16:15
Same issue as tannisroot.  Only using this integration for 3 Sonoff Micro.  When using local mode it shows 0/3 cloud devices online and 3/3 local devices online, but the switch itself is unavailable.

Hoping to get local mode working reliably so I can block web access on the micros.

**Comment by tannisroot** [comment] 2022-09-28 23:14
> Same issue as tannisroot. Only using this integration for 3 Sonoff Micro. When using local mode it shows 0/3 cloud devices online and 3/3 local devices online, but the switch itself is unavailable.
> 
> Hoping to get local mode working reliably so I can block web access on the micros.

If you set mode to Auto and block internet access, it will work locally just fine. It's only when you specify local mode that it breaks.

**Comment by AlexxIT** [comment] 2022-11-15 11:30
It seems that a lot of people have problems with local mode. I think the changes to the zeroconf operation didn't help. And it needs to be reworked again.

**Comment by 7system7** [comment] 2022-12-13 15:28
I have the same issue. :cry: After the latest upgrade, nothing worked.

```
 Home Assistant 2022.12.4
 Supervisor 2022.11.2
 Operating System 9.4
 Frontend 20221212.0 - latest 
```

### Logs

```
Logger: homeassistant.loader
Source: components/zeroconf/__init__.py:18
First occurred: 16:20:40 (4 occurrences)
Last logged: 16:20:53

Unexpected exception importing component homeassistant.components.zeroconf
Unexpected exception importing platform homeassistant.components.hue.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 709, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 18, in <module>
    from zeroconf import InterfaceChoice, IPVersion, ServiceStateChange
  File "/usr/local/lib/python3.10/site-packages/zeroconf/__init__.py", line 26, in <module>
    from ._core import Zeroconf
  File "/usr/local/lib/python3.10/site-packages/zeroconf/_core.py", line 36, in <module>
    from ._handlers import (
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
```

```
Logger: homeassistant.setup
Source: setup.py:200
First occurred: 16:20:44 (2 occurrences)
Last logged: 16:20:48

Unable to set up dependencies of sonoff. Setup failed for dependencies: zeroconf
Unable to set up dependencies of default_config. Setup failed for dependencies: zeroconf
```

**Comment by AlexxIT** [comment] 2023-02-06 03:55
I hope this should be fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0

**Closed by AlexxIT** 2023-02-06 03:55 UTC
Labels: bug

**Comment by RuSPanzer** [comment] 2023-02-06 08:11
I have installed the new version and confirm that https://github.com/AlexxIT/SonoffLAN/issues/1012 is fixed for sure, thanks!

**Comment by Seemone** [comment] 2023-02-06 08:38
I confirm 3.4.0 solves this issue for me, I upgraded from 3.2.0.
many thanks!
