### ISSUE TITLE
Sonoff RFBridge433 - SONOFF PIR3-RF - state does not change on motion

### ISSUE THREAD

**Issue by ripcam21** [AlexxIT/SonoffLAN#859] opened 2022-05-25 03:56 UTC
I have noticed that the Sonoff bridge, when paired with the Sonoff PIR3-RF and set as an alarm, the state of the sensor is always set to clear, even after motion is triggered.  The state works well in the ewelink app, however, home assistant is not recognising the state change when motion triggered.

![RFBridge433](https://user-images.githubusercontent.com/106219466/170176311-00b1ff42-59ca-4e24-a946-0e3a6fdb24e4.JPG)
![Sonoff PIR-RF](https://user-images.githubusercontent.com/106219466/170176324-ca111f81-1ac9-48c1-8baa-71801ac176d1.JPG)
![image](https://user-images.githubusercontent.com/106219466/170177068-b2f99cee-534a-46fa-9912-2263df00a8ef.png)

**Comment by pieterhill** [comment] 2022-07-04 18:46
I have tried with button class and motion class but no state change is detected. I find sensors wiht the old naming convention still work fine e.g. binary_sensor.big_store_pir but if I update the automation to the new naming convention binary_sensor.1000cdecf5_0 then it no longer works.

**Comment by leexion1** [comment] 2022-07-08 03:42
same  since the plugin updated.

**Comment by rexopl** [comment] 2022-07-22 19:56
I have the same problem with Dual R3.
I use them for 2 level fan control.
When calling service - they react and fun is running but status is not changed.
When I reload addon it looks like then is status updated once and than is not working again.

This is happening ~ month since some updates.
My system is 100% up to date and running official hassio.

**Comment by AlexxIT** [comment] 2022-07-25 18:49
You need provide component debug logs in moment sensor triggered.

**Comment by Kydonakis** [comment] 2022-09-01 06:58
Any updates on this? Is it now fixed?

**Comment by AlexxIT** [comment] 2022-09-24 19:50
I haven't seen any useful information about the bug, so it's not fixed.

**Comment by Kydonakis** [comment] 2022-09-24 20:02
I confirm that PIR3-RF works as intended in home assistant. No bug at all so I guess if it was something at the time, now is fixed.

**Comment by AlexxIT** [comment] 2023-03-31 12:17
Please reopen the issue if it is still relevant

**Closed by AlexxIT** 2023-03-31 12:17 UTC
Labels: bug
