### ISSUE TITLE
Ability to control auto settings in THR316D?

### ISSUE THREAD

**Issue by olalofgren** [AlexxIT/SonoffLAN#1263] opened 2023-11-29 09:19 UTC
I have the Sonoff THR316D and have successfully connected it through Sonoff LAN to Home Assistant.

But I'm not able to control the auto settings in the device. This would be useful when using it as a thermostat.

Is that something that is possible to do, and is it something that's coming?

**Comment by AlexxIT** [comment] 2023-11-29 09:21
If you want, you can do it with https://github.com/AlexxIT/SonoffLAN#raw-commands

**Comment by olalofgren** [comment] 2023-11-29 09:34
Thanks! I'll look into those and see if I can make it work. Any plans to integrate it into the integration beyond the raw commands?

**Comment by AlexxIT** [comment] 2023-11-29 10:23
I don't see the benefit. Usually such things are set up once and for a long time. This can be done in the original application.

**Comment by olalofgren** [comment] 2023-11-29 10:43
For me, I would like to use the auto function in the switch as the thermostat. So in case the switch loses connection with Home Assistant, the thermostat keeps working on its own. But I still want to use Home Assistant to set the temperature.

**Comment by olalofgren** [comment] 2023-11-29 12:11
Ideally for me the switch could be configured to show up as a climate entity in HA

**Comment by AlexxIT** [comment] 2023-11-29 13:00
Climate supported for first model. I don't remember why it's not supported for your model. Maybe different API.

https://github.com/AlexxIT/SonoffLAN/blob/45f72d9d192432547503737e8b4cdeb73a682ae1/custom_components/sonoff/core/devices.py#L153

**Comment by olalofgren** [comment] 2023-11-29 13:59
Yeah. Found this now.
https://github.com/AlexxIT/SonoffLAN/issues/1074

I have the device, can I help somehow to enable support?

**Comment by AlexxIT** [comment] 2023-11-29 14:38
Only if you implement this functionality yourself. I don't think I have time for that in the near future.
I'll close this issue as duplicate of 1074.

**Closed by AlexxIT** 2023-11-29 14:38 UTC
Labels: question
