### ISSUE TITLE
Ewelink device becomes unavailable

### ISSUE THREAD

**Issue by simclancy** [AlexxIT/SonoffLAN#335] opened 2021-01-04 13:37 UTC
I am having an issue when a certain ewelink device becomes unavailable and i am unable to trigger it to turn off, the issue is only solved with me restarting my home assistant instance. The device doesnt lose connection to the internet as i can see that on my Unifi controller. 

I can control the device from the ewelink app with no issues.

**Comment by AlexxIT** [comment] 2021-01-31 10:23
Show your config

**Comment by dwf** [comment] 2021-01-31 14:06
Also seeing this with two Sonoff Micros in local mode. They somewhat frequently stop responding (incorrectly report state, don't respond to on/off service calls) but everything works once I restart HA.

My config is literally just

```
sonoff:
  mode: local
```

Plus the retrieved data from the API stored in `.sonoff.json` of course.

**Comment by AlexxIT** [comment] 2021-01-31 19:08
Maybe your micros change their IP address?

**Comment by dwf** [comment] 2021-01-31 22:58
They are statically mapped in my DHCP server, also this can happen within a few seconds of a successful command, i.e. I'll toggle it in Home Assistant and though the switch turns on, the entity state in Home Assistant fails to update, and stays wrong until I restart Home Assistant.

**Comment by AlexxIT** [comment] 2021-02-01 04:54
Check readme about problems in local mode

**Comment by dwf** [comment] 2021-02-01 11:27
Noticed this in the log:
```
2021-02-01 10:43:35 ERROR (Sonoff_LAN) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1755, in run
self._service_state_changed.fire(
File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1513, in fire
h(**kwargs)
File "/config/custom_components/sonoff/sonoff_local.py", line 170, in _zeroconf_handler
for k, v in info.properties.items()
AttributeError: 'NoneType' object has no attribute 'properties'
```

**Comment by AlexxIT** [comment] 2021-02-02 08:26
What fw has your micro?

**Comment by pomah86** [comment] 2021-02-02 16:20
Hi, I have a similar issue, but it seems like I can not control my devices at all through HASSIO, but I can control them perfectly using the eWeLink app.

I get this issue in the log:
`Logger: homeassistant.helpers.integration_platform
Source: loader.py:429
First occurred: 17:13:36 (4 occurrences)
Last logged: 17:13:36

Unexpected error importing sonoff/media_source.py
Unexpected error importing sonoff/group.py
Unexpected error importing sonoff/logbook.py
Unexpected error importing sonoff/system_health.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.Sonoff.media_source'`

This is my config:
`#Sonoff
sonoff:
  devices:
    1000abcdefg:
      devicekey: my key`

The interesting note is that when switching the TH16 (using eWeLink) I can see the status in real time in HASSIO, but I can not trigger the switch in HASSIO, only see the status, so the TH16 seems to be connected, just not being able to control it.

**Comment by dwf** [comment] 2021-02-06 21:19
@AlexxIT Sorry that I couldn't get around to this until now. I had one running 3.4.0 and one running 3.6.0 with the same issue. I just updated them both to 3.7.1 and the issue persists. Local control works for a while, and then it becomes unresponsive (but still controllable in Ewelink).

I just realized I'm running a slightly old version of the addon, so I will update and check if it persists.

**Comment by dwf** [comment] 2021-02-07 02:12
To update: yes, the problem is still there with the newer version. `get_service_info` seems to periodically return None for me. I can see the mDNS responses on my network when I tcpdump on the router, so I'm not quite sure what's going on.

I wonder would there be a way to cache data from Zeroconf to avoid this, since once a device is discovered its IP and so on probably won't change. Happy to try and help with this.

**Comment by AlexxIT** [comment] 2021-02-08 08:45
@dwf what version of your HA?

**Comment by pomah86** [comment] 2021-02-08 09:22
Hi, I can just make a short update, after a few restarts and removing adding my TH16 to the eWelink app it is now functioning as intended. I even blocked the TH16 from internet access and have now after a few days removed the eWelink app completely from my phone.

So my suggestions is to remove/add the device again and try if that solves the issue.

**Comment by dwf** [comment] 2021-02-08 10:41
HA 2021.01.7. I will try updating to the latest version, as well.

**Comment by AlexxIT** [comment] 2021-02-08 14:45
@pomah86 there are no such files in my component. As shown in your log

**Comment by AlexxIT** [comment] 2021-02-08 14:48
@dwf I'll try to add Micro to my setup. I have it, but I never used it.

**Comment by pomah86** [comment] 2021-02-09 08:37
@AlexxIT 

Below is the system I am running, nothing special as far as I know, I should mention that I do run this addon without HACS

## System Health

version | core-2021.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.94
arch | x86_64
timezone | Europe/Stockholm

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.11
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.5
docker_version | 19.03.13
disk_total | 109.3 GB
disk_used | 12.3 GB
healthy | true
supported | true
board | intel-nuc
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), deCONZ (6.6.5), Duck DNS (1.12.4), Spotify Connect (0.8.2), Mosquitto broker (5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 8
mode | storage

</details>

**Comment by AlexxIT** [comment] 2021-03-10 04:45
Empty zeroconf response fixed in latest master version. Usual users has wrong network config when get this error

**Comment by AlexxIT** [comment] 2021-03-10 19:40
Empty zeroconfig fixed in latest release

**Closed by AlexxIT** 2021-03-10 19:40 UTC
Labels: bug, question
