### ISSUE TITLE
Unavailable after reboot or some time

### ISSUE THREAD

**Issue by Monacoslo** [AlexxIT/SonoffLAN#72] opened 2020-04-04 23:57 UTC
After HA reboot my devices are Unavailable untill I manually trigger them in eWelink application. Same issue is also after some time not using them even without HA reboot.

Any sollution? Maybe to "ping" them somehow or sth?

**Comment by prosymnus** [comment] 2020-04-09 05:17
same here. T1 switch unavailable every time restart the HA.

**Comment by LennyLip** [comment] 2020-04-11 20:02
https://github.com/AlexxIT/SonoffLAN/issues/72

**Comment by LennyLip** [comment] 2020-04-12 04:47
ups, sorry https://github.com/AlexxIT/SonoffLAN/issues/68

**Comment by mantaalex** [comment] 2020-04-16 23:14
im having the issue to hopefully someone could fix it please report someone if fixed :) tx

**Comment by tawagny** [comment] 2020-04-21 20:02
same here , I tried to add them again and it worked but again something went wrong

**Comment by AlexxIT** [comment] 2020-04-24 12:42
All devices unavailable after restart. It does not depend on reload once / always setting.
Devices are automatically detected in the local network after each restart.
If this does not happen, there are some problems with the multicast / router.

**Comment by AlexxIT** [comment] 2020-05-04 07:20
@mattsaxon do you know how to force device descovery after HA reboot?
Sometimes devices appear quickly. Sometimes after a few minutes.

**Comment by mattsaxon** [comment] 2020-05-04 07:24
I’ve not had this problem with my component. That is likely because it doesn’t use discovery. I note that your component returns if there is no discovery data passed,  but I’m not clear why you do that, since you have all the information from your saved cache to setup your zeroconf instance.

**Comment by AlexxIT** [comment] 2020-05-04 07:32
@mattsaxon problem with zeroconf discovery. Devices do not always respond quickly.
Of course, I can save the IP addresses of devices before reboot. But it's not a very nice solution.

**Comment by mattsaxon** [comment] 2020-05-04 07:53
I’ve not had any problems with zeroconf response time. I don’t think you should save IPs. I assumed the issue for your component is due to HA not passing the discovery info, not due to zeroconf itself.

**Comment by mattsaxon** [comment] 2020-05-04 17:53
To be clear, I wondering if this piece of code is related to the delay

```
    if discovery_info is None:
        return
```

Though to be fair I haven't understood what is populating this info or what calls it, it just feels as if that is passed from HA's discovery component and those device ids are available to you already in the cache rather than needing to be passed from HA discovery process.

**Comment by AlexxIT** [comment] 2020-05-05 07:02
@mattsaxon I think the problem is with the router. For some users, the problem appears more often, for some less often.

**Comment by mattsaxon** [comment] 2020-05-05 07:11
Agreed. If you implement the approach as discussed In issue #79, I think this will be a lot more acceptable to users as they will see the device greyed out at startup and then come online.

One issue is that any automations however will fail as you can’t automate a device which is unavailable.

A potential approach to fix this is to provide a config setting that states if the device is persistent. ie should never be unavailable. This would allow users to configure if you should always have marked as available in home Assistant and then implement some retry logic to deal with the poor network.

I myself haven’t had to implement the setting in my component, but did implement the retry logic.

**Comment by AlexxIT** [comment] 2020-05-11 13:51
Try new version #99

**Comment by mattsaxon** [comment] 2020-05-17 13:37
@AlexxIT the new version gives some errors for me. I have some notification in the UI that the component isn't setup correctly. I end up with no working devices, but a set of devices named as "Sonoff [device_id]" rather than the usual situation where they have the name from eWeLink.

I'm using HA 0.109.6.

**Comment by AlexxIT** [comment] 2020-05-26 07:48
Version 2 should handle all the problems.

**Closed by AlexxIT** 2020-05-26 07:48 UTC
Labels: enhancement
